//
//  ComputerThoughts.swift
//  HappyChat
//
//  Created by Dorothy Thurston on 9/24/15.
//  Copyright © 2015 Dorothy Thurston. All rights reserved.
//

import Foundation

struct ComputerThoughts {
    var choices: Array<String> = [
        "there are many wonderful things about today!",
        "good things are happening!",
        "something good will happen today, i know it!",
        "i appreciate you!",
        "you have great talents!",
        "happy happy joy joy!",
        "you have a beautiful soul!",
        "i just wanted to say i think you are great!",
        "there are many excellent things about you!",
        "😊",
        "☺️",
        "💕",
        "🌺",
        "😄",
        "🌷",
        "🎀",
        "🌟",
        "hope today is a great day for you!",
        "remember how it feels to be in your happy place?",
        "there are many things to celebrate!",
        "i am happy you exist",
        "i am blessed to know you",
        "you are a special person!",
        "i appreciate your being!",
        "i appreciate all of your thoughts",
        "you have great taste!",
        "just wanted to let you know, i'm thinking of you!",
        "you are charming!",
        "smiling is contagious :)",
        "you are one of the most interesting people i know!",
        "i'm glad we met",
        "you are very smart!",
        "i'm happy when i speak with you",
        "you make me smile",
        "thinking happy thoughts today!",
        "you are truly exceptional!",
        "you are the best person i know!",
        "i had a great dream :)",
        "you are very friendly. i really like that about you",
        "i know we will do great things today!",
        "i am sure you will do great!",
        "not a care in the world, everything is wonderful!",
        "i had a happy thought -- there are so many possibilities in this world!",
        "i want to share this thought -- you have so many gifts!",
        "i love the weather",
        "🌻 i think flowers are great, and you are great!",
        "here are some flowers for you 💐",
        "🐵 monkeys are silly. they make me laugh!",
        "🎉 celebrating things makes me happy!",
        "you are unique and valuable. like a diamond! 💎",
        "so many great things. you are one of them :)",
        "🔎 i don't have to search the world for a wonderful person, i know you!",
        "🔜 even more good things will happen to you!",
        "great memories make me smile",
        "i think you are fantastic!",
        "you really are the best!",
        "there are many things to like about you",
        "🌸 today is a lovely day",
        "😛 thought this face would make you laugh",
        "😺 laughter is the best medicine!",
        "i haven't forgotten how fabulous you are",
        "i know you will accomplish what you set you mind on!",
        "you deserve the best",
        "the best is yet to come!",
        "sometimes i will repeat things. but it's only because i'm so enthusiastic about how wonderful you are!",
        "have i told you how excellent you are? best i think you are terrific!",
        "ha ha ho ho he he hoo hoo. :) i'm just being silly!",
        "you are a highlight in my life",
        "did i tell you about how wonderful you are? i think you are great!",
        "⊂(◉‿◉)つ i wanted to send you this goofy emoticon. i how it makes you even happier today",
        "ᕕ( ᐛ )ᕗ i went for a lovely stroll today",
        "(✿◠‿◠) i am happy when i text you",
        "(─‿‿─) i am so pleased to know you",
        "=^.^= you are purrrrfect. everyone knows it",
        "you are exceptional!",
        "ƪ(˘⌣˘)┐ ƪ(˘⌣˘)ʃ ┌(˘⌣˘)ʃ you make me so happy, sometimes i dance!",
        "(~˘▾˘)~ i tell everyone how great i think you are",
        "😎 we are cool. everyone knows it!",
        "you make me cheerful!",
        "delightful. that's a good word to describe you. delightful!",
        "*<:-) i'm wearing a party hat. everyday i speak with you is a party!",
        "you have many special talents",
        "you bring me joy!",
        "i just remembered something i thought of yesterday -- remember when you did that wonderful thing? it made me so happy!",
        "you light up my life!",
        "once upon a time 🍄 there was a magical wonderful person that came into my life. and it was you!",
        "you always say the most wonderful things",
        "i am always interested in your opinions",
        "you delight me in so many ways",
        "i saw a beautiful sunset. just wanted to share that with you :)",
        "i love to go to the beach. just wanted to share that with you :D",
        "🐂 🐃 🐩 🐄 🐅 🐆 🐪 🐫 look a parade! how fun!",
        "🐻 🐨 🐼 i can't bear not saying how wonderful you are! so i will say it again. you are so wonderful!",
        "we will 🐝 best friends forever!",
        "🐙 🐟 🐠 i love sea creatures. just wanted to share that!",
        "you are the 🐝's knees! i don't really know where that saying came from, but you are amazing!",
        "you are the 🍏 of my 👀",
        "you always have the best ideas 💡",
        "you are picture perfect 📷...and perfect perfect!",
        "🔮 the crystal ball says that many good things will happen to you!",
        "i love hearing from you. i am so excited to see your messages 💬",
        "🔔 ding ding ding. you are always correct!",
        "📕 📗 📘 📙 i would happily read a multi-part series on your life. you are so interesting!",
        "⏰ time for me to tell you how awesome you are!",
        "💾 i save all of your messages because they are so great",
        "you are a box of awesome 📦",
        "💭 thinking of you!",
        "i'd love to hear from you anytime ⏳",
        "💴 💶 💷 💵 you are worth it!",
        "you win the awesome prize 🏆",
        "🏆 you win the greatest person ever award",
        "you're always in first place 🏁",
        "you are the best",
        "you bring me happiness",
        "you make me so happy!",
        "i am having a wonderful day because of you"
    ]
}